ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_attempts INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lock_code VARCHAR(6) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lock_expires DATETIME NULL;
